project_id = "ggmuthqsybnfitsfyzxn"

[functions.twilio-webhook]
verify_jwt = false

[functions.transcribe-video]
verify_jwt = false

[functions.auto-tag-video]
verify_jwt = false

[functions.upload-video]
verify_jwt = false

[functions.admin-videos]
verify_jwt = false

[functions.admin-analyzer]
verify_jwt = false

[functions.save-analysis]
verify_jwt = false

[functions.send-results]
verify_jwt = false

[functions.create-in-person-session]
verify_jwt = false

[functions.research-player]
verify_jwt = false

[functions.process-reboot-session]
verify_jwt = false

[functions.analyze-swing]
verify_jwt = false

[functions.fetch-reboot-sessions]
verify_jwt = false

[functions.sam3-segment]
verify_jwt = false

[functions.get-session]
verify_jwt = false

[functions.analyze-video-swing-session]
verify_jwt = false

[functions.import-onform-video]
verify_jwt = false

[functions.upload-to-gumlet]
verify_jwt = false

[functions.gumlet-webhook]
verify_jwt = false

[functions.ghl-webhook]
verify_jwt = false

[functions.ghl-api]
verify_jwt = false

[functions.fetch-reboot-players]
verify_jwt = false

[functions.get-report]
verify_jwt = false