project_id = "ggmuthqsybnfitsfyzxn"

[functions.twilio-webhook]
verify_jwt = false

[functions.transcribe-video]
verify_jwt = false

[functions.auto-tag-video]
verify_jwt = false

[functions.upload-video]
verify_jwt = false

[functions.admin-videos]
verify_jwt = false

[functions.admin-analyzer]
verify_jwt = false

[functions.save-analysis]
verify_jwt = false

[functions.send-results]
verify_jwt = false

[functions.create-in-person-session]
verify_jwt = false